AWSTemplateFormatVersion: 2010-09-09
Description: >-
  PhotoMe
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: pr
    AllowedValues:
      - pr
      - drr
    Description: Environment name for resource naming

Globals:
  Function:
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment

Conditions:
  IsPrimaryRegion: !Equals
    - !Ref "AWS::Region"
    - eu-west-1

Resources:
  # Cognito
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "PhotoMeUserPool-${Environment}"
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
        - Name: name
          AttributeDataType: String
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub "PhotoMeAppClient-${Environment}"
      GenerateSecret: true
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - https://main.d1dz6uduz5w2pj.amplifyapp.com/dashboard
      LogoutURLs:
        - https://main.d1dz6uduz5w2pj.amplifyapp.com/signout

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub "PhotoMeIdentityPool-${Environment}"
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ProviderName: !GetAtt CognitoUserPool.ProviderName
          ClientId: !Ref CognitoUserPoolClient

  PhotoBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "photome-bucket-amalitech-sam-${Environment}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ReplicationRole:
    Type: AWS::IAM::Role
    Condition: IsPrimaryRegion
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:GetObjectVersionForReplication
                Resource:
                  - !Sub "arn:aws:s3:::photome-bucket-amalitech-sam-pr/*"
                  - !Sub "arn:aws:s3:::photome-bucket-amalitech-sam-drr/*"

  S3ReplicationConfig:
    Type: AWS::S3::Bucket
    Condition: IsPrimaryRegion
    Properties:
      BucketName: !Sub "photome-bucket-amalitech-sam-pr"
      ReplicationConfiguration:
        Role: !GetAtt ReplicationRole.Arn
        Rules:
          - Status: Enabled
            Priority: 1
            DeleteMarkerReplication:
              Status: Enabled
            Destination:
              Bucket: !Sub "arn:aws:s3:::photome-bucket-amalitech-sam-drr"
            Filter:
              Prefix: ""

  photoTable:
    Type: AWS::DynamoDB::Table
    Condition: IsPrimaryRegion
    Properties:
      TableName: !Sub "photo-${Environment}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
